const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
  OPEN_EXTRA_DROP_DOWN_MENU: 'OPEN_EXTRA_DROP_DOWN_MENU',
};

export default ShopActionTypes;
